DATASET:
  SEQUENCE_LENGTH: 7
  SEQUENCE_STRIDE: 1
  SUBDIR_INPUTS: ''
  TEST_ROOT_DIRS: []
  TRAIN_ROOT_DIRS: ['/media/yaroslav/SSD970PRO/Huawei/datasets/vimeo_septuplet/test']
  TYPE: DCVCSequenceDataset
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
INPUT:
  IMAGE_SIZE: [128, 128]
  MAKE_DIVISIBLE_BY: 8
MODEL:
  ARCHITECTURE: DCVC_HEM
  DEVICE: cuda
OUTPUT_DIR: outputs/test
SOLVER:
  BATCH_SIZE: 1
  LR: 0.0002
  MAX_EPOCH: 128
TENSORBOARD:
  BEST_SAMPLES_NUM: 16
  WORST_SAMPLES_NUM: 16