CUTOUT_LAYER:
  DETECTORS:
    FACES:
      DEVICE: 'cuda'
      ENABLE: True
      PADDING: 10
      PROB: 0.8
    LIPLATES:
      DEVICE: 'cuda'
      ENABLE: False
      PADDING: 0
      PROB: 0.6
  H265:
    CRF: 13
    PIX_FMT: 'yuv444p'
    PRESET: 'veryfast'
VIDEO_LAYER:
  H265:
    CRF: 25
    PIX_FMT: 'gbrp'
    PRESET: 'veryfast'
  VSR_MODEL:
    ARCHITECTURE: 'FTVSR'
    DEVICE: 'cuda'
    CHUNK_SIZE: 10
    MID_CHANNELS: 64
    NUM_BLOCKS: 60
    TILE_PADDING: 16
    TILE_SIZE: 160
    WEIGHTS_PATH: 'outputs/ftvsr/model_009591.pth'
